version: '3.7'

services:
  lego:
    image: goacme/lego
    env_file:
      - ./.env
    command: >
      --email ${CERTBOT_EMAIL}
      --dns pdns
      --domains ${CONSOLE_FQDN}
      --domains ${API_FQDN}
      --path /lego
      --accept-tos
      run
    volumes:
      - lego-certificates:/.lego

  minio:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASS:-minio123}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
      MINIO_BROWSER_REDIRECT_URL: https://${CONSOLE_FQDN}
      MINIO_SERVER_URL: https://${API_FQDN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - /mnt/data1:/data

  nginx:
    image: nginx:1.21.1
    volumes:
      - ./nginx/conf.d:/etc/nginx/templates:ro
      - lego-certificates:/etc/nginx/certs
    environment:
      - CONSOLE_HOST=${CONSOLE_FQDN}
      - API_HOST=${API_FQDN}
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - minio
      - lego

volumes:
  lego-certificates:
